# Generated by Django 4.2.5 on 2023-11-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('C', 'Comunidad USM'), ('E', 'Estudiante'), ('P', 'Profesor'), ('J', 'Jefe de Carrera')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_Inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('titulo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(1, 'Vacaciones'), (2, 'Feriado'), (3, 'Suspension de actividades'), (4, 'Suspension de actividades PM'), (5, 'Período Lectivo'), (6, 'Suspension de evaluciones'), (7, 'Ceremonia'), (8, 'EDDA'), (9, 'Evaluación'), (10, 'Ayudantias'), (11, 'Hito Académico'), (12, 'Secretaría Académica'), (13, 'OAI')], default=1)),
                ('asociacion', models.ManyToManyField(to='core.segmento')),
            ],
        ),
    ]
